---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-pv
  namespace: ollama
spec:
  storageClassName: ""
  claimRef:
    name: ollama-pvc
    namespace: ollama
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/k8s/ollama
    server: cplane1 # IP or name of master like: cplane1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: ollama
spec:
  storageClassName: ""
  volumeName: ollama-pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
