apiVersion: v1
kind: PersistentVolume
metadata:
  name: openwebui-pv
  namespace: ollama
spec:
  storageClassName: ""
  claimRef:
    name: openwebui-pvc
    namespace: ollama
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/k8s/openwebui
    server: cplane1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-pvc
  namespace: ollama
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: openwebui-pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webui
  template:
    metadata:
      labels:
        name: webui
    spec:
      containers:
        - name: webui
          image: ghcr.io/open-webui/open-webui:main
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /app/backend/data
              name: openwebui-pv-storage
          env:
            - name: OLLAMA_BASE_URLS
              value: "http://ollama"
          ports:
            - name: webui-http
              containerPort: 8080
              protocol: TCP
      volumes:
        - name: openwebui-pv-storage
          persistentVolumeClaim:
            claimName: openwebui-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: webui
  namespace: ollama
spec:
  type: NodePort
  selector:
    name: webui
  ports:
    - port: 8080
      name: http
      targetPort: webui-http
      nodePort: 30080
