---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openwebui-pv
  namespace: ollama
spec:
  storageClassName: ""
  claimRef:
    name: openwebui-pvc
    namespace: ollama
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/k8s/openwebui
    server: cplane1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-pvc
  namespace: ollama
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: openwebui-pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
